apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-server
  namespace: default
  labels:
    app: jupyter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-server
  template:
    metadata:
      labels:
        app: jupyter-server
    spec:
      containers:
        - name: jupyter
          image: jupyter/base-notebook:latest
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /api/
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: jupyter-server
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30081
      protocol: TCP

